# Generated by Django 5.1.7 on 2025-03-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
