# Generated by Django 5.1.7 on 2025-03-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_houserent_product_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseRent',
            new_name='Rent',
        ),
    ]
